config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about'
  resources :postimages, only:[:new, :index, :show, :create, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
  end

  resources :users, only:[:show, :edit, :update]



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/postimage.rb
class Postimage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates:shop_name, presence:true
  validates:image, presence:true

  def get_image
    unless image.attached?
      file_path =Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/postimages_controller.rb
class PostimagesController < ApplicationController
  def new
    @postimage = Postimage.new
  end

  def create
    @postimage = Postimage.new(postimage_params)
    @postimage.user_id = current_user.id
    if @postimage.save
      redirect_to postimages_path
    else
      render :new
    end
  end

  def index
    @postimages = Postimage.page(params[:page])
    
  end

  def show
    @postimage = Postimage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @postimage = Postimage.find(params[:id])
    @postimage.destroy
    redirect_to postimage_path
  end

  private

  def postimage_params
    params.require(:postimage).permit(:shop_name, :image, :caption)
  end
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/views/postimages/_list.html.erb
<div class="card-list-container py-5">
  <% postimages.each do |postimage| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to postimage_path(postimage.id) do %>
      <%= image_tag postimage.get_image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag postimage.user.get_profile_image(100, 100), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(postimage_path(postimage.id), class:"text-dark") do %>
              <strong><i class="far fa-fing"></i><span><%= postimage.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明:<%= postimage.caption %></p>
          <span><i class="fas fa-user"></i>BY <%= postimage.user.name %> | </span>
          <span><%= link_to "#{postimage.post_comments.count} コメント",postimage_path(postimage.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate postimages %>
</div>

app/views/postimages/index.html.erb
<%= render 'list', postimages: @postimages %>
<!--<%#render [部分テンプレートファイルの指定],[ローカル変数]: [渡す値] %>-->

app/views/postimages/new.html.erb
<dib class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @postimage.errors.any? %>
        <ul class="alert alert-danger" role="alert">
          <h6 class="alert-heading">
            <%= @postimage.errors.count %>件のエラーが発生しました
          </h6>
          <% @postimage.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @postimage do |f| %>
        <%= f.file_field :image, accept: "image/*", class: "w-100" %>
        <div class="input-group mb-3 mt-4">
          <div class="input-group-prepend">
            <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
          </div>
          <%= f.text_field :shop_name, class:"form-control",placeholder:"ショップ名" %>
        </div>
        <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに"  %>
        <hr>
        <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
      <% end %>  
          
  

app/views/postimages/show.html.erb
<div>
  <%= image_tag @postimage.get_image %>
  <p>ショップ名:<%= @postimage.shop_name %></p>
  <p>説明:<%= @postimage.caption %></p>
  <p>ユーザーネーム:<%= @postimage.user.name %>></p>
  <p>投稿日:<%= @postimage.created_at.strftime('%Y/%m/%d') %></p>
  <% if @postimage.user == current_user %>
    <%= link_to "削除", postimage_path(@postimage), method: :delete %>
  <% end %>

  <% if @postimage.favorited_by?(current_user) %>
    <p>
      <%= link_to postimage_favorites_path(@postimage), method: :delete do %>
       ♡<%= @postimage.favorites.count %>いいね
       <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to postimage_favorites_path(@postimage),method: :post do %>
        ♡<%= @postimage.favorites.count %>いいね
        <% end %>
    </p>
    <% end %>
</div>

<div>
  <p>コメント件数:<%= @postimage.post_comments.count %></p>
  <% @postimage.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100, 100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", postimage_post_comment_path(post_comment.postimage, post_comment), method: :delete %>
    <% end %>

  <% end %>
</div>

<div>
  <%= form_with model: [@postimage, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
    <% end %>
</div>